In [3]:
# Import necessary libraries

import numpy as np
import pandas as pd

# Keras tools for NLP and deep learning
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [2]:
!pip install numpy pandas

   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.3/11.3 MB ? eta -:--:--
   ------- -------------------------------- 2.1/11.3 MB 9.8 MB/s eta 0:00:01
   ---------- ----------------------------- 2.9/11.3 MB 8.4 MB/s eta 0:00:02
   ----------- ---------------------------- 3.1/11.3 MB 5.8 MB/s eta 0:00:02
   -------------- ------------------------- 4.2/11.3 MB 5.0 MB/s eta 0:00:02
   ----------------- ---------------------- 5.0/11.3 MB 4.6 MB/s eta 0:00:02
   -------------------- ------------------- 5.8/11.3 MB 4.5 MB/s eta 0:00:02
   --------------------- ------------------ 6.0/11.3 MB 4.4 MB/s eta 0:00:02
   ------------------------- -------------- 7.3/11.3 MB 4.2 MB/s eta 0:00:01
   --------------------------- ------------ 7.9/11.3 MB 4.0 MB/s eta 0:00:01
   ------------------------------- -------- 8.9/11.3 MB 4.1 MB/s eta 0:00:01
   --------------------------------- ------ 9.4/11.3 MB 3.9 MB/s eta 0:00:01
   ----------

In [4]:
# Simple dataset

texts = [
    "I love this movie",
    "This movie is good",
    "I hate this movie",
    "This movie is bad"
]

labels = [1,1,0,0]  # 1 = Positive, 0 = Negative


In [5]:
# Create tokenizer object

tokenizer = Tokenizer()

# Learn vocabulary from texts

tokenizer.fit_on_texts(texts)

# Convert sentences into numbers

sequences = tokenizer.texts_to_sequences(texts)

print(sequences)


[[3, 5, 1, 2], [1, 2, 4, 6], [3, 7, 1, 2], [1, 2, 4, 8]]


In [6]:
# Make all sequences same length

X = pad_sequences(sequences, maxlen=5)

print(X)


[[0 3 5 1 2]
 [0 1 2 4 6]
 [0 3 7 1 2]
 [0 1 2 4 8]]


In [7]:
# Convert labels to array

y = np.array(labels)


In [8]:
# Create model

model = Sequential()

# Embedding Layer
model.add(
Embedding(
input_dim=100,
output_dim=8,
input_length=5
)
)


c:\Users\kabir\anaconda3\envs\tf_env\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [9]:
# Add LSTM layer

model.add(LSTM(8))


In [10]:
# Output layer

model.add(Dense(1, activation='sigmoid'))


In [11]:
# Prepare model for training

model.compile(
loss='binary_crossentropy',
optimizer='adam',
metrics=['accuracy']
)


In [12]:
# Train model

model.fit(X,y,epochs=20)


Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.2500 - loss: 0.6931
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.2500 - loss: 0.6929
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7500 - loss: 0.6927
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7500 - loss: 0.6925
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7500 - loss: 0.6923
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7500 - loss: 0.6921
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.7500 - loss: 0.6919
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7500 - loss: 0.6917
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7500 - loss: 0.6914
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7500 - loss: 0.6912
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.6910
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.6908
Epo

In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 5, 8)           │           800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 8)              │           544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,061 (15.87 KB)

 Trainable params: 1,353 (5.29 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2,708 (10.58 KB)

In [18]:
# Test sentence

test = ["This movie is worst"]

# Convert to numbers

seq = tokenizer.texts_to_sequences(test)

# Padding

pad = pad_sequences(seq,maxlen=5)

# Prediction

pred = model.predict(pad)

print(pred)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
[[0.49808195]]


In [19]:
if pred > 0.5:
    print("Positive")
else:
    print("Negative")


Negative
